export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_CHECK_FROM_LS = "AUTH_CHECK_FROM_LS";
export const LOGOFF = "LOGOFF";

export const PERMISSION_SUCCESS = "PERMISSION_SUCCESS";
export const UPDATE_PERMISSION = "UPDATE_PERMISSION";
